### ISSUE TITLE
Adding Dynamic Taints to Nodes based on Tolerations

### ISSUE THREAD

**Issue by VishDev12** [kubernetes-sigs/karpenter#746]
**Tell us about your request**

Using this [scheduling technique](https://karpenter.sh/v0.14.0/tasks/scheduling/#exists-operator), it's possible to add a custom label to a node based on a corresponding key/value pair specified in the node-selector or node-affinity. This allows us to have nodes from a single provisioner that have differing custom labels based on the workloads that get scheduled on them, and ultimately, this allows for workload isolation at the node level.

But this is only true if every pod using that provisioner specifies that custom label in the node-selector or node-affinity. If a workload doesn't specify it, it can now be scheduled on any node launched by the provisioner and isolation is no longer a guarantee.

It seems that in addition to dynamic labelling, a mechanism to dynamically taint the nodes would help guarantee workload isolation at the node level. This would be critical for multi-tenant scenarios where it's one thing to say that isolation is 'possible', but with this feature, isolation would be inviolable.

@ellistarn had the suggestion of defining taints in the provisioner with an empty or '*' value and then specifying the corresponding tolerations in the workload.

Taint specified in the provisioner:

```yaml
- key: company.com/team
  value: "*"
  effect: NoSchedule
```

Toleration:

```yaml
- key: company.com/team
  value: datascience
  effect: NoSchedule
```

If the corresponding toleration is not specified in the workload, the understanding is that the node on which it will be scheduled never gets a taint. This allows both isolated and non-isolated workloads to use the same provisioner.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

In a multi-tenant scenario, we prefer to have workloads cleanly segregated by nodes. Currently this is achievable by creating a new provisioner where the clear expectation is that everyone using it is expected to either have the custom label specified in the node-selector or node-affinity, and this would be what determines the workload isolation because their workloads would always be scheduled on nodes with matching labels. But what would be more ideal is to be able to do this directly from the default provisioner where both isolated and non-isolated workloads are able to coexist with it being impossible for the non-isolated pods to be scheduled on the isolated nodes.

**Me being greedy**

The above would be more than cool enough already. But if it's possible to do away with the necessity of specifying the custom labels or taints on the provisioner, that would be the ultimate level of flexibility. Unlimited node groups controlled by nothing but the workloads. Perhaps something along these lines:

```yaml
nodeSelector:
  customLabel/company.com/team: datascience

tolerations:
  - key: customLabel/company.com/team
    value: datascience
    effect: NoSchedule
```

The expectation being that when Karpenter sees 'customLabel/' in the nodeSelector, it understands that it needs to generate a corresponding node label. The same would apply for generating taints when it sees the 'customLabel/' prefix in the tolerations.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by GnatorX** [comment]
Going to revive this thread

> Do you have any thoughts on how you would expect some of the edge-cases to behave in the case where the ordering of pods causes non-deterministic behavior similar to the scenarios that are listed in the discussion above?

I can give some insight into what I am looking into @jonathan-innis.

### Number of NodePools
I have a larger use case, I am talking about hundreds of Node Pool vs 1-2 Node Pool because we want to provide isolation between "services". 

### Edge case discussion
IMO the non-deterministic behavior is expected. The reason for this is if a pod is asking to land on a node with no taints because it has no toleration we need a node without taints. This also means that there is also no expectation for this pod to land on an isolated node because it doesn't have toleration. On the other hand since the second pod didn't have a node selector, there is no expectation of the node it runs on hence it ran on a node with another pod from a different team.

I don't see this as a bug nor a feature because there is a difference between what taint does and what node selector does and we shouldn't expect convergence of behavior just because order of operation is different nor should we solve for convergence of this behavior. This feels like saying we have "inconsistent" behavior if we set node affinity and node selector differently we they do behave differently and have different expectation.

**Comment by njtran** [comment]
Adding a TLDR on this thread for those who are coming back to this more recently. When you need to ensure different tenants don't schedule onto the same node, you can orchestrate this different ways. 

- Create a nodepool for each tenant, ensuring that only one tenant is compatible with each nodepool. This ensures a node-level isolation on your pods. This results in a higher number of NodePools, often having very small differences.
- Create anti affinity on hostname to ensure that pods you don't want to schedule with your pods, aren't. This requires a lot of configuration on the deployment side, which could be a nuisance for app teams, but also is a less performant way to reason about scheduling for Karpenter + kube-scheduler.

Both of the above workarounds have downsides of moving further away from Karpenter best practices. If Karpenter supports a `*` value in their taints, Karpenter could generally say that any pod with a matching toleration key will be compatible, where the value of the taint on the node is then the value on the pod's toleration. Yet, this only ensures isolation if pods are also selecting on a set of compatible NodePools, preventing bad acting tolerating pods from racing and potentially resulting in nodes without taints (not ensuring tenant-isolation)

**Comment by mikkeloscar** [comment]
We had a desire for a similar feature as requested in this issue. Our goals were:

1. Minimize number of node pools
2. Allow _some_ workloads to opt-in to run on isolated nodes.

We implemented a "hybrid" solution where we define two node pools. One has no requirements or taints, and the other has:

```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
spec:
  template:
    spec:
     ...
      requirements:
        - key: isolate
          operator: Exists
     taints:
     - key: isolate
       operator: Exists
       effect: NoSchedule
```

And pods who wish to run isolated define a nodeSelector and toleration:

```yaml
spec:
  nodeSelector:
    isolate: custom-isolation-key # can be team/application name etc.
  tolerations:
    - key: "isolate"
      operator: Exists
      effect: NoSchedule
```

This way, pods without the requirement land on the first pool without requirement/taint and can't land on the isolated node because they don't have a toleration.
Pods that do want it will land on isolated nodes based on nodeSelector.

Maybe this is helpful for others looking at this.

(We further simplify the definition on pod by simply having users add an annotation and then we generate/inject the nodeSelector toleration via mutating webhook. This is just a UX detail).

**Comment by GnatorX** [comment]
Is there a reason we closed the PR? Wanted to see if we can still get this feature
